#!/bin/sh

abort() {
	printf "\n  \033[31mError: $@\033[0m\n\n" && exit 1
}

ok() {
	printf "\n  \033[32mOk: $@\033[0m\n\n"
}

load_env() {
	_DIR="."
	ENVFILE_BASE="${1:-$_DIR}/.env-base"
	ENVFILE_OPT="${1:-$_DIR}/.env-${2:-development}"
	if test ! -e $ENVFILE_BASE -o ! -e $ENVFILE_OPT; then
		abort "Environment file not found"
	fi

	set -a
	. ${ENVFILE_BASE}
	. ${ENVFILE_OPT}
	set +a
}

gen_env() {
	GEN_ENV="./gen_env"
	_PADRAO='../resource/env.js'
	OUT="${1:-$_PADRAO}/.env-${2:-development}"
	if test -f $GEN_ENV; then
		$(${GEN_ENV} > ${OUT})
		ok "ENVs para o front gerado... ${OUT}"
	fi
}
