#!/bin/sh

abort() {
	printf "\n  \033[31mError: $@\033[0m\n\n" && exit 1
}

ok() {
	printf "\n  \033[32mOk: $@\033[0m\n\n"
}

load_env() {
	_DIR="$(pwd)"
	ENVFILE_BASE="${2:-$_DIR}/.env-base"
	ENVFILE_OPT="${2:-$_DIR}/.env-${1:-development}"
	if test ! -e $ENVFILE_BASE -o ! -e $ENVFILE_OPT; then
		abort "Environment file not found"
	fi

	set -a
	. ${ENVFILE_BASE}
	. ${ENVFILE_OPT}
	set +a
}

gen_env() {
	_DIR=$(dirname "$0")
	GEN_ENV="${2:-$_DIR}/gen_env"

	if test -z $1; then
		abort "Missing output"
	fi

	if test -f $GEN_ENV; then
		$GEN_ENV > $1
		ok "ENVs generated... ${1}"
	fi
}
