#!/bin/bash

DIR="$(cd -P "$(dirname "$0")" && pwd)"

# Import functions
. $DIR/_fn

# Go to project root
cd $DIR
cd ..

CURR_FOLDER="$(pwd)"
OPT="development"
COMPOSE_TEMPLATE="${CURR_FOLDER}/docker-compose.template.yml"
COMPOSE_LOCAL="${CURR_FOLDER}/docker-compose.local.yml"

export DOCKERFILE="${CURR_FOLDER}/Dockerfile.dev"

# ENV File
load_env $OPT

docker-compose \
	-f $COMPOSE_TEMPLATE \
	-f $COMPOSE_LOCAL \
	down \
	--volumes \
	--remove-orphans

test $? -ne 0 && abort "Docker Compose down failed" || ok "Stopped"

exit 0
