#!/bin/sh

DIR="$(cd -P "$(dirname "$0")" && pwd)"

# Import functions
. $DIR/_fn

# Go to current directory
CURR_FOLDER="$(pwd)"
cd $CURR_FOLDER

ok "Running cmd: ${WATCH_CMD}"

# Watch command
$WATCH_CMD

if test $? -ne 0; then
	abort "Watch failed"
fi

exit 0
