#!/bin/bash

DIR="$(cd -P "$(dirname "$0")" && pwd)"

# Import functions
. $DIR/_fn

# Go to current directory
CURR_FOLDER="$(pwd)"
cd $CURR_FOLDER

OPT=development

# ENV File
load_env $OPT

# Generate ENVs for frontend application
if test "${REQUIRE_GEN:-0}" = "1"; then
	gen_env "${CURR_FOLDER}/resource/env.js"
fi

ok "Running cmd: ${WATCH_CMD}"

# Watch command
$WATCH_CMD

if test $? -ne 0; then
	abort "Watch failed"
fi

exit 0
